# Generated by Django 3.1.2 on 2020-11-04 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID INSTRUMENTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción del instrumento.', max_length=1000)),
            ],
        ),
    ]
